export const SET_USER = 'PROFILE_ACTION:SET_USER';
export const SET_IS_LOADING = 'PROFILE_ACTION:SET_IS_LOADING';
export const SET_EXPANDED_EDIT_IMAGE_PROFILE = 'PROFILE_ACTION:SET_EXPANDED_EDIT_IMAGE_PROFILE';
export const SET_EXPANDED_EDIT_USERNAME_PROFILE = 'PROFILE_ACTION:SET_EXPANDED_EDIT_USERNAME_PROFILE';
export const SET_EXPANDED_EDIT_STATUS_PROFILE = 'PROFILE_ACTION:SET_EXPANDED_EDIT_STATUS_PROFILE';
export const EDIT_PROFILE = 'PROFILE_ACTION:EDIT_PROFILE';
export const TOGGLE_STATUS = 'PROFILE_ACTION:TOGGLE_STATUS';
